# Generated by Django 5.1.5 on 2025-02-08 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_recruiter_company_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joboffer',
            name='recruiter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.recruiter'),
        ),
        migrations.AlterField(
            model_name='recruiter',
            name='company_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='recruiter',
            name='company_website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
